version: '3'

services:
  timesheet-entry:
    image: nginx:latest
    volumes:
      - ./nginx/application.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - timesheet-backend
      - timesheet-ui

  timesheet-backend:
    image: manedev79/timesheet
    expose:
      - "8080"

  timesheet-ui:
    image: manedev79/timesheet-ui
    expose:
      - "80"
    depends_on: 
      - timesheet-backend

